### ISSUE TITLE
Connection Scheme

### ISSUE THREAD

**Issue by JulianRave** [Joostytibo/EVAL-ADXL355Z#2]
Hi, I'm trying to use this project, but it's not clear to me with the connection. Should you show me a picture of this connection between Arduino UNO and EVAL-ADXL355Z?

**Comment by Joostytibo** [comment]
Hi, sorry for the late reply.

SDA = A4 on the Arduino
SCL = A5 on the Arduino
VDD = 3.3V on the Arduino
GND = GND on the arduino

The connection:

![image](https://user-images.githubusercontent.com/74665616/118398045-2723ce00-b657-11eb-8fad-82d366436aff.png)

**Comment by JulianRave** [comment]
Thanks a lot!

**Comment by djsg** [comment]
UNO IO pin level is 5V, while ADXL355 IO pin max level is 3.6V.
I wonder if your board is spoiled or it runs just fine.

**Comment by Joostytibo** [comment]
> 

Hi, for me the board runs just fine. What I saw in the datasheet was an absolute maximum rating for VDDIO = 5.4V. Take this to the absolute maximum rating on the pins from ADXL355 which says: "-0.3V to VDDIO +0.3V". So I thought it should be between 5.1V and 5.7V. Correct me if I'm wrong, because it was nearly a year ago when I made this.
See datasheet ADXL354_355 --> page 8

**Comment by djsg** [comment]
Thx for the info. I didn't see that max rating.
I will give it a try.

**Comment by djsg** [comment]
your VDD and GND are which two pins?
